version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: backend_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    command: npm run dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_local
    restart: always
    env_file: .env  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
